server:
  port: 8088    #springboot内置tomcat启动端口
spring:
  redis:        #redis连接
    host: 127.0.0.1
    password: 12345678
    port: 6379
    database: 0
  datasource:   #mysql连接
    url: jdbc:mysql://117.50.9.91:3306/imoxin_poem_dev
    username: imoxin_poem
    password: imoxin_poem
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations: classpath:mapper/*.xml   #生成的mapper.xml位置